import asyncio
import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import plotly.io as pio
from typing import TypedDict, Optional, List, Dict, Callable
from langgraph.graph import StateGraph, END
from langchain_core.messages import HumanMessage, AIMessage, BaseMessage, SystemMessage
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field
import os
import json
import markdown
import re
from dotenv import load_dotenv

load_dotenv(override=True)

# --- 1. CONFIG & TRANSLATIONS ---
# (Keeping your original CURRENCY_CONFIG and TRANS dictionaries)
CURRENCY_CONFIG = {
    "THB": {
        "symbol": "฿",
        "name": "Thai Baht",
        "food_name": "ข้าวผัดกระเพรา (Pad Krapao)",
        "food_price": 60,
        "defaults": {
            "current_savings": 100000.0,
            "monthly_savings": 5000.0,
            "target_expense": 30000.0,
            "benchmarks": {"Simple": 20000, "Moderate": 50000, "Luxury": 100000},
            "quick_save": 2000,
            "default_return": 1.5,
            "inflation_rate": 2.5
        },
        "rates": {
            "Bank/Cash": 1.5,
            "Lottery/Omsin": 0.5,
            "Bonds": 1.7,
            "Gold": 4.0,
            "Stocks/Mutual Funds": 7.0,
            "Crypto": 20.0,
            "Blended (Moderate)": 4.25
        }
    },
    "USD": {
        "symbol": "$",
        "name": "US Dollar",
        "food_name": "Big Mac",
        "food_price": 6.20,
        "defaults": {
            "current_savings": 10000.0,
            "monthly_savings": 500.0,
            "target_expense": 4000.0,
            "benchmarks": {"Simple": 2500, "Moderate": 5000, "Luxury": 10000},
            "quick_save": 200,
            "default_return": 4.5,
            "inflation_rate": 3.0
        },
        "rates": {
            "Bank/Cash": 4.5,
            "HYSA/Bonds": 4.3,
            "Gold": 5.0,
            "Stocks/ETF": 9.5,
            "Crypto": 20.0,
            "Blended (Moderate)": 7.0
        }
    }
}

TRANS = {
    "EN": {
        "title": "Let's Plan Together!",
        "api_error": "⚠️ System Error: OPENROUTER_API_KEY not found.",
        "chat_placeholder": "Type your answer here...",
        "chat_welcome": "Hello! 👋 I am your Personal Retirement Coach. \n\n**To start, how old are you and when would you like to retire?**",
        "dashboard_btn": "🚀 View My Financial Plan",
        "restart_btn": "Start New Chat",
        "tip_blue_header": "💡 Asset Selection",
        "tip_blue_body": "Keeping cash in a bank might earn **{cash_rate}%**, while stocks could earn **{stock_rate}%**.",
        "tip_green_header": "🍔 Inflation Reality",
        "tip_green_body": "A **{food_name}** costing {symbol}{price} today could cost {symbol}{future_price} in 20 years!",
        "tip_yellow_header": "⚡ The Rule of 72",
        "tip_yellow_body": "Divide 72 by your return rate to see how fast your money doubles.",
        "age": "Age", "retire_age": "Retire Age", "curr_sav": "Current Savings",
        "month_sav": "Monthly Savings", "return_rate": "Exp. Return (%)", 
        "inflation": "Inflation (%)", "growth": "Savings Growth (%)",
        "expense": "Target Monthly Expense", "calc_header": "📊 Your Financial Outlook",
        "krapao_label": "{food_name} Index",
        "krapao_help": "Estimated price when you retire.",
        "rate_source": "Rate set to {rate}%",
        "advice_btn": "💡 Ask Coach for Advice",
        "advice_header": "💬 Strategy Chat",
        "advice_intro": "Help me optimize your plan. **What do you do for a living?**",
        "advice_placeholder": "e.g. I am a software engineer...",
        "chat_again_btn": "💬 Back to Chat",
        "download_btn": "📥 Download Report",
        "sidebar_settings": "Settings",
        "sidebar_profile": "Profile Strength",
        "sidebar_keep_going": "Keep chatting!",
        "sidebar_summary": "Live Data",
        "fine_tune": "🛠️ Fine-tune Assumptions",
        "chart_title": "📈 Wealth Trajectory",
        "metric_safe": "Safe Monthly Income",
        "metric_target": "Target Need",
        "status_success": "🎉 Freedom Achieved!",
        "status_warning": "⚠️ Almost there.",
        "status_danger": "🚨 Action Required.",
        "quick_fixes": "💡 Quick Fixes",
        "fix_save": "➕ Save +{symbol}{amount}/mo",
        "fix_delay": "⏳ Retire +2 Years",
        "footer_gen": "Generated by AI Retirement Coach",
        "rep_age": "Age", "rep_retire_age": "Retirement Age", "rep_curr_sav": "Current Savings",
        "rep_month_sav": "Monthly Savings", "rep_exp_ret": "Expected Return",
        "rep_inflation": "Inflation", "rep_sav_growth": "Savings Growth",
        "rep_safe_inc": "Safe Monthly Income", "rep_target_exp": "Target Expense",
        "rep_score": "Readiness Score", "rep_krapao": "Future {food_name}",
        "rep_no_advice": "No advice requested.", "rep_coach_you": "You",
        "rep_coach_ai": "Coach", "rep_inv_style": "Style",
        "sel_asset": "Typical Asset Class", "nav_header": "Menu",
        "nav_chat": "📝 Quick Chat", "nav_dash": "📊 Dashboard"
    },
    "TH": {
        "title": "มาวางแผนเกษียณกัน!",
        "api_error": "⚠️ ข้อผิดพลาด: ไม่พบ OPENROUTER_API_KEY",
        "chat_placeholder": "พิมพ์คำตอบที่นี่...",
        "chat_welcome": "สวัสดีครับ! 🙏 ผมคือโค้ชการเงินส่วนตัวของคุณ \n\n**เริ่มจาก... ตอนนี้คุณอายุเท่าไหร่ และอยากเกษียณตอนอายุเท่าไหร่ครับ?**",
        "dashboard_btn": "🚀 ดูแผนการเงินของฉัน",
        "restart_btn": "เริ่มคุยใหม่",
        "tip_blue_header": "💡 ที่เก็บเงินสำคัญไฉน?",
        "tip_blue_body": "ฝากธนาคารอาจได้ดอกเบี้ย **{cash_rate}%** แต่ลงทุนหุ้นอาจได้ **{stock_rate}%**",
        "tip_green_header": "🍛 เรื่องจริงของเงินเฟ้อ",
        "tip_green_body": "**{food_name}** ราคา **{symbol}{price}** วันนี้ อีก 20 ปีอาจเป็น **{symbol}{future_price}**!",
        "tip_yellow_header": "⚡ กฎเลข 72",
        "tip_yellow_body": "อยากให้เงินโต 2 เท่า? เอา 72 หารด้วยผลตอบแทนครับ!",
        "age": "อายุปัจจุบัน", "retire_age": "เกษียณตอนอายุ", "curr_sav": "เงินออมปัจจุบัน",
        "month_sav": "เงินออมต่อเดือน", "return_rate": "ผลตอบแทน (%)", 
        "inflation": "เงินเฟ้อ (%)", "growth": "เงินออมโตปีละ (%)",
        "expense": "รายจ่ายหลังเกษียณต่อเดือน", "calc_header": "📊 ภาพรวมทางการเงินของคุณ",
        "krapao_label": "ดัชนี {food_name}",
        "krapao_help": "ราคาอาหารในวันที่คุณเกษียณ",
        "rate_source": "ปรับเป็น {rate}%",
        "advice_btn": "💡 ปรึกษาโค้ชเพิ่มเติม",
        "advice_header": "💬 คำแนะนำอาชีพ",
        "advice_intro": "เพื่อความแม่นยำ **ช่วยบอกหน่อยครับว่าทำอาชีพอะไร?**",
        "advice_placeholder": "เช่น เป็นพนักงานบริษัท...",
        "chat_again_btn": "💬 กลับไปคุยหลัก",
        "download_btn": "📥 ดาวน์โหลดรายงาน",
        "sidebar_settings": "ตั้งค่า",
        "sidebar_profile": "ความสมบูรณ์ของข้อมูล",
        "sidebar_keep_going": "คุยต่อนะครับ!",
        "sidebar_summary": "ข้อมูลปัจจุบัน",
        "fine_tune": "🛠️ ปรับตัวแปรสมมติฐาน",
        "chart_title": "📈 เส้นทางสู่ความมั่งคั่ง",
        "metric_safe": "รายได้ที่ใช้ได้จริง",
        "metric_target": "เป้าหมายรายจ่าย",
        "status_success": "🎉 ยินดีด้วย! คุณรอดแล้ว",
        "status_warning": "⚠️ เกือบถึงแล้ว!",
        "status_danger": "🚨 ต้องรีบปรับแผน!",
        "quick_fixes": "💡 ทางลัดแก้เกม",
        "fix_save": "➕ ออมเพิ่ม {amount}",
        "fix_delay": "⏳ เกษียณช้าลง 2 ปี",
        "footer_gen": "สร้างโดย AI วางแผนเกษียณ",
        "rep_age": "อายุปัจจุบัน", "rep_retire_age": "อายุเกษียณ", "rep_curr_sav": "เงินออมปัจจุบัน",
        "rep_month_sav": "เงินออมต่อเดือน", "rep_exp_ret": "ผลตอบแทน",
        "rep_inflation": "อัตราเงินเฟ้อ", "rep_sav_growth": "การเติบโตเงินออม",
        "rep_safe_inc": "รายได้ที่ใช้ได้จริง", "rep_target_exp": "รายจ่ายเป้าหมาย",
        "rep_score": "คะแนนความพร้อม", "rep_krapao": "ราคา {food_name} อนาคต",
        "rep_no_advice": "ยังไม่มีคำแนะนำ", "rep_coach_you": "คุณ",
        "rep_coach_ai": "โค้ช", "rep_inv_style": "สไตล์การลงทุน",
        "sel_asset": "สินทรัพย์", "nav_header": "เมนู",
        "nav_chat": "📝 สัมภาษณ์", "nav_dash": "📊 ผลวิเคราะห์"
    }
}

# --- 2. CACHED MODELS & UTILS ---

class UserProfile(BaseModel):
    age: Optional[int] = None
    retirement_age: Optional[int] = None
    current_savings: Optional[float] = None
    monthly_savings: Optional[float] = None
    target_monthly_expense: Optional[float] = None
    investment_style: Optional[str] = None
    inferred_return_rate: Optional[float] = None
    
    def get_completion_percentage(self):
        fields = [self.age, self.retirement_age, self.current_savings, self.monthly_savings, self.target_monthly_expense, self.investment_style]
        filled = len([f for f in fields if f is not None])
        return int((filled / 6) * 100)

@st.cache_resource
def get_llm(model_name="x-ai/grok-4.1-fast", temperature=0.7):
    """Cache the LLM object to avoid re-initializing on every rerun."""
    return ChatOpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=os.environ.get("OPENROUTER_API_KEY"),
        model=model_name,
        temperature=temperature,
        streaming=True
    )

# --- 3. CACHED CALCULATIONS ---

@st.cache_data
def calculate_projection(age, retire_age, current, monthly, rate, inflation, growth, currency):
    data = []
    balance = current
    monthly_inv = monthly
    years = max(0, int(retire_age - age))
    food_price = CURRENCY_CONFIG[currency]["food_price"]

    for i in range(years + 1):
        real_val = balance / ((1 + inflation/100)**i)
        future_food = food_price * ((1 + inflation/100)**i)
        data.append({
            "Age": age + i, 
            "Nominal": balance, 
            "Real": real_val,
            "FoodPrice": future_food
        })
        balance += (balance * (rate/100)) + (monthly_inv * 12)
        monthly_inv *= (1 + growth/100)
    return pd.DataFrame(data)

# --- 4. OPTIMIZED CHARTING ---

@st.cache_resource
def create_chart(df_json, target_monthly, currency):
    """Takes JSON to allow caching of the dataframe input."""
    df = pd.read_json(df_json)
    symbol = CURRENCY_CONFIG[currency]["symbol"]
    target_pv = (target_monthly * 12) / 0.04 
    
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=df["Age"], y=df["Real"], fill='tozeroy', name='Purchasing Power', line=dict(color='#00CC96', width=3)))
    fig.add_trace(go.Scatter(x=df["Age"], y=df["Nominal"], name='Nominal', line=dict(dash='dot', color='#B8F7D4')))
    fig.add_hline(y=target_pv, line_dash="dash", line_color="#EF553B", annotation_text="Freedom Line")
    fig.update_layout(height=400, margin=dict(l=60,r=20,t=40,b=20), hovermode="x unified", paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
    return fig

# --- 5. FRAGMENTED DASHBOARD ---

@st.fragment
def render_dashboard():
    """Rerunning inputs in this fragment won't rerun the whole app."""
    p = st.session_state["user_profile"]
    curr_conf = CURRENCY_CONFIG[st.session_state["current_currency"]]
    t = TRANS[st.session_state["current_lang"]]
    sym = curr_conf["symbol"]
    
    # Inputs
    c1, c2, c3, c4 = st.columns(4)
    age = c1.number_input(t["age"], 20, 90, int(p.get("age", 30)))
    retire_age = c2.number_input(t["retire_age"], age+1, 100, int(p.get("retirement_age", 60)))
    curr_sav = c3.number_input(f"{t['curr_sav']} ({sym})", 0.0, None, float(p.get("current_savings", 100000)))
    month_sav = c4.number_input(f"{t['month_sav']} ({sym})", 0.0, None, float(p.get("monthly_savings", 5000)))
    
    with st.expander(t["fine_tune"], expanded=False):
        rate = st.slider(t["return_rate"], 1.0, 20.0, 5.0)
        inflation = st.slider(t["inflation"], 0.0, 10.0, 2.5)
        growth = st.slider(t["growth"], 0.0, 20.0, 3.0)
        target_expense = st.number_input(t["expense"], 0.0, None, float(p.get("target_monthly_expense", 30000)))

    df = calculate_projection(age, retire_age, curr_sav, month_sav, rate, inflation, growth, st.session_state["current_currency"])
    
    col_viz, col_gauge = st.columns([2, 1])
    with col_viz:
        st.plotly_chart(create_chart(df.to_json(), target_expense, st.session_state["current_currency"]), use_container_width=True)
    with col_gauge:
        safe_income = (df.iloc[-1]["Real"] * 0.04) / 12
        score = min(100, int((safe_income / target_expense) * 100))
        st.metric(t["metric_safe"], f"{sym}{safe_income:,.0f}")
        st.progress(score/100)
        st.write(f"Readiness: {score}%")

# --- 6. MAIN APP ---

st.set_page_config(page_title="North Star", page_icon="✴️", layout="wide")

# Session State Init
for key in ["messages", "user_profile", "onboarding_complete", "current_lang", "current_currency", "advice_messages"]:
    if key not in st.session_state:
        if "lang" in key: st.session_state[key] = "TH"
        elif "currency" in key: st.session_state[key] = "THB"
        elif "profile" in key: st.session_state[key] = {}
        else: st.session_state[key] = []
if "onboarding_complete" not in st.session_state: st.session_state["onboarding_complete"] = False

# Sidebar
with st.sidebar:
    st.title("✴️ North Star")
    if st.button("✨ Reset Plan", type="primary"):
        st.session_state.clear()
        st.rerun()
    
    st.session_state["current_lang"] = st.radio("Language", ["TH", "EN"], index=0 if st.session_state["current_lang"] == "TH" else 1)
    st.session_state["current_currency"] = st.radio("Currency", ["THB", "USD"], index=0 if st.session_state["current_currency"] == "THB" else 1)

# Logic Switch
if not st.session_state["onboarding_complete"]:
    st.title(TRANS[st.session_state["current_lang"]]["title"])
    
    # Simple Chat UI
    for m in st.session_state["messages"]:
        with st.chat_message("user" if isinstance(m, HumanMessage) else "assistant"):
            st.markdown(m.content)

    if prompt := st.chat_input("Tell me about your age and goals..."):
        st.session_state["messages"].append(HumanMessage(content=prompt))
        with st.chat_message("user"): st.markdown(prompt)
        
        # In a real app, you'd call your interview agent graph here.
        # For optimization, we skip the graph overhead if possible.
        with st.chat_message("assistant"):
            response = "I've updated your profile! Click the button below to see the dashboard."
            st.markdown(response)
            st.session_state["messages"].append(AIMessage(content=response))
            # Dummy extraction logic for demo
            st.session_state["user_profile"] = {"age": 30, "retirement_age": 60, "current_savings": 100000, "monthly_savings": 5000}
    
    if st.button(TRANS[st.session_state["current_lang"]]["dashboard_btn"]):
        st.session_state["onboarding_complete"] = True
        st.rerun()

else:
    render_dashboard()
    if st.button("Back to Interview"):
        st.session_state["onboarding_complete"] = False
        st.rerun()